# Generated by Django 3.1.7 on 2021-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(max_length=200, unique=True)),
                ('usefor', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
                ('idc_id', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(default=0)),
                ('ssl_start_date', models.CharField(blank=True, default='0000-00-00', max_length=200)),
                ('ssl_expire_date', models.CharField(blank=True, default='0000-00-00', max_length=200)),
                ('remaining_time', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
            ],
        ),
    ]
