# Generated by Django 3.1.7 on 2021-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='usefor',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myapp',
            name='cName',
            field=models.CharField(max_length=200),
        ),
    ]
