# Generated by Django 3.1.7 on 2021-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210412_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='enddate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myapp',
            name='limit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myapp',
            name='startdate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
